baseURL = "https://unclecui233.github.io/"
languageCode = "zh-cn"
title = "LowBee 的博客"
theme = "blowfish"
defaultContentLanguage = "zh-cn"

[pagination]
  pagerSize = 10

[languages]
  [languages.zh-cn]
    languageName = "简体中文"
    weight = 1

[params]
  defaultTheme = "auto"
  colorScheme = "blowfish"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 20
