# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = "https://unclecui233.github.io/"
defaultContentLanguage = "zh-cn"
relativeURLs = false
canonifyURLs = true

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true
hasCJKLanguage = true

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[pagination]
  pagerSize = 10

[imaging]
  anchor = 'Center'
  quality = 75
  resampleFilter = 'CatmullRom'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "index"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
