[zh-cn]
  languageCode = "zh-cn"
  languageName = "简体中文"
  weight = 1
  title = "LowBee 的博客"

[zh-cn.params]
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006年1月2日"
  description = "分享技术文章和个人见解的博客"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # promoLogo = "img/promo-logo.png"
  # favicon = "img/favicon.png"
  # fingerprint = ""
  # copyright = "© 2023"

[zh-cn.author]
  name = "LowBee"
  image = ""
  headline = "热爱技术的开发者"
  bio = "欢迎来到我的技术博客！"
  links = [
    # { email = "mailto:hello@your_domain.com" },
    # { github = "https://github.com/username" },
    # { twitter = "https://twitter.com/username" },
  ]
